EMAIL TEMPLATE


{{-- resources/views/emails/report.blade.php --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        .header {
            background: linear-gradient(135deg, #065f46, #047857);
            color: white;
            padding: 20px;
            text-align: center;
            margin: -30px -30px 30px -30px;
            border-radius: 10px 10px 0 0;
        }
        .summary {
            background: #f0f9ff;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .summary h3 {
            color: #0369a1;
            margin-top: 0;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .data-table th {
            background-color: #065f46;
            color: white;
        }
        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ $reportTitle }}</h1>
            <p>{{ $reportData['period'] ?? 'Generated on ' . now()->format('Y-m-d H:i:s') }}</p>
        </div>

        @if(isset($reportData['summary']))
        <div class="summary">
            <h3>Report Summary</h3>
            <ul>
                @foreach($reportData['summary'] as $key => $value)
                    <li>
                        <strong>{{ ucwords(str_replace('_', ' ', $key)) }}:</strong>
                        @if(is_array($value))
                            <ul>
                                @foreach($value as $subKey => $subValue)
                                    <li>{{ ucwords(str_replace('_', ' ', $subKey)) }}: {{ $subValue }}</li>
                                @endforeach
                            </ul>
                        @else
                            {{ $value }}
                        @endif
                    </li>
                @endforeach
            </ul>
        </div>
        @endif

        @if(isset($reportData['data']) && count($reportData['data']) > 0)
        <h3>Detailed Data</h3>
        <table class="data-table">
            <thead>
                <tr>
                    @foreach(array_keys((array)$reportData['data'][0]) as $header)
                        <th>{{ ucwords(str_replace('_', ' ', $header)) }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach(array_slice($reportData['data'], 0, 20) as $row)
                    <tr>
                        @foreach($row as $value)
                            <td>{{ is_array($value) ? json_encode($value) : $value }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
        @if(count($reportData['data']) > 20)
            <p><em>Showing first 20 records of {{ count($reportData['data']) }} total records.</em></p>
        @endif
        @endif

        <div class="footer">
            <p>This report was automatically generated by the Hiking Platform Report System.</p>
            <p>If you have any questions, please contact the system administrator.</p>
        </div>
    </div>
</body>
</html>