# Nixpacks Configuration for Railway
# Let Nixpacks auto-detect Laravel and use default PHP setup

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --only=production"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
