# Nixpacks Configuration for Railway
# This tells Railway how to build and deploy your Laravel application

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.bcmath", "php82Extensions.exif", "nodejs-20_x"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "npm ci --only=production"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
